version: "3.8"
services:
  frontend:
    image: 127.0.0.1:5000/kyw-frontend:latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - infra
  backend-persister:
    image: 127.0.0.1:5000/kyw-backend:latest
    command: ["persister", "listen"]
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_PORT=5432
      - DB_NAME=kyw
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    networks:
      - infra
      - internal
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: kyw
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal


networks:
  infra:
    external: true
  internal:
    driver: overlay
